name: Build

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          git
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-clang
          mingw-w64-x86_64-ninja

    - name: Build and Package apple-libtapi
      run: |
        git clone --depth=1 https://github.com/tpoechtrager/apple-libtapi -b 1600.0.11.8
        cd apple-libtapi
        sed -i 's/FileRenameInfoEx/FileRenameInfo/g' src/llvm/lib/Support/Windows/Path.inc
        sed -i 's/FILE_RENAME_INFO_EX/FILE_RENAME_INFO/g' src/llvm/lib/Support/Windows/Path.inc
        sed -i 's/#if defined(HAVE_UNISTD_H)/#if defined(HAVE_UNISTD_H) \&\& !defined(_WIN32)/g' src/llvm/lib/CAS/CachingOnDiskFileSystem.cpp
        sed -i '1i #include <cstdint>' src/llvm/lib/Target/AMDGPU/MCTargetDesc/AMDGPUMCTargetDesc.h || true
        
        mkdir build && cd build
        cmake -G "Ninja" \
          -DCMAKE_BUILD_TYPE=Release \
          -DLLVM_INCLUDE_TESTS=OFF \
          -DLLVM_TARGETS_TO_BUILD="AArch64;ARM" \
          -DCMAKE_C_COMPILER=/mingw64/bin/clang.exe \
          -DCMAKE_CXX_COMPILER=/mingw64/bin/clang++.exe \
          -DCMAKE_INSTALL_PREFIX=/mingw64 \
          ../src/llvm
        ninja
        
        mkdir -p ${{ github.workspace }}/tapi_dist
        DESTDIR=${{ github.workspace }}/tapi_dist cmake --install .

    - name: Upload Prebuilt TAPI Toolchain
      uses: actions/upload-artifact@v4
      with:
        name: apple-libtapi-mingw64-standalone
        path: ${{ github.workspace }}/tapi_dist/mingw64/
